choria-io/asyncjobs

- .github/workflows/test.yaml
> (misc) configure basic testing action

- client.go
- client_options.go
- client_test.go
- go.mod
- go.sum
- processor.go
- queue.go
- storage.go
- storage_test.go
> (misc) fix ginkgo module imports

- client_test.go
- retrypolicy_test.go
- task.go
- task_test.go
> (misc) add additional test coverage

- README.md
- client_examples_test.go
- client_test.go
> (misc) add some godoc

- client.go
- client_examples_test.go
- mux.go
- processor.go
- queue.go
- storage.go
> (misc) more godoc and minor updates

- README.md
> (misc) add basic logo

- ajc/info_command.go
- ajc/main.go
- ajc/task_command.go
- ajc/util.go
- client_options.go
- go.mod
- go.sum
- processor.go
- retrypolicy.go
- stats.go
- storage.go
> (misc) utility to run tasks via shell scripts

- .gitignore
- .goreleaser.yaml
- Dockerfile.goreleaser
- README.md
- ajc/info_command.go
- ajc/main.go
- ajc/queue_command.go
- ajc/task_command.go
- ajc/util.go
- client.go
- mux.go
- mux_test.go
- processor.go
- processor_test.go
- retrypolicy_test.go
- stats.go
- storage.go
- storage_test.go
- task.go
* Queue management
* Ability to terminate retries from a handler
* Goreleaser addition
> (misc) various CLI and mux improvements

- .github/workflows/codeql.yaml
- README.md
> (misc) set up codeql

- README.md
> (misc) update readme

- README.md
> (misc) further readme updates

- README.md
> (misc) badges

- ajc/main.go
- ajc/util.go
- client.go
- client_options.go
- retrypolicy.go
- stats.go
- storage.go
> (misc) address go lint issues

- README.md
- ajc/task_command.go
- client.go
- go.mod
- go.sum
> (misc) address go lint issue and some docs

- README.md
- ajc/queue_command.go
- ajc/task_command.go
- ajc/util.go
- client_options.go
- go.mod
- go.sum
> (misc) support queue add on the cli

- README.md
- ajc/main.go
- ajc/task_command.go
- client.go
- client_options.go
> (misc) Add tasks init to prepare initial task storage

- client.go
- client_options.go
- client_test.go
- go.mod
- go.sum
> (#27) support discarding tasks in end states

- README.md
- ajc/task_command.go
- client.go
- processor.go
- queue.go
- storage.go
- storage_test.go
> (#29) allow tasks to be retried

- ajc/task_command.go
- lifecycle.go
> (#15) minor updates to lifecycle events

- client.go
- client_test.go
- errors.go
- lifecycle.go
- mux.go
- mux_test.go
- processor.go
- processor_test.go
- storage.go
- storage_test.go
> (#35) extract errors to promote use of errors.Is()

- README.md
> (misc) make the readme more approachable and informative

- Dockerfile.goreleaser
- README.md
- ajc/main.go
- ajc/package_command.go
- ajc/task_command.go
- ajc/util.go
- client_examples_test.go
- client_test.go
- generators/fs/godocker/Dockerfile.templ
- generators/fs/godocker/main.go.templ
- generators/godocker.go
- generators/package.go
- go.mod
- mux.go
- mux_test.go
- processor.go
- processor_test.go
Also adjust the handler signature to include a Logger
that will make creating reusable handlers easier and
more portable
> (#43) support packaging handlers into docker containers

- ajc/package_command.go
> (#43) fix using own version in packager

- generators/fs/godocker/Dockerfile.templ
- generators/godocker.go
- generators/package.go
> (#43) support and require a package version for handlders

- ajc/package_command.go
> (#43) cosmetic updates to packages

- ajc/package_command.go
- ajc/task_command.go
- errors.go
- generators/fs/godocker/main.go.templ
- generators/godocker.go
- generators/package.go
- go.mod
- go.sum
- mux.go
- request_reply_handler.go
- request_reply_handler_test.go
- storage.go
Also support for them in docker packager
> (#19) support request-reply handlers

- README.md
> (misc) minor readme update

- errors.go
- processor.go
- processor_test.go
- stats.go
- task.go
> (#53) support task max tries

- ajc/task_command.go
- processor.go
> (#53) CLI support for max tries

- ajc/info_command.go
- ajc/queue_command.go
- ajc/task_command.go
- ajc/task_cron_command.go
- ajc/util.go
- asyncjobs.go
- client.go
- election/election.go
- election/election_test.go
- election/options.go
- election/stats.go
- errors.go
- go.mod
- go.sum
- processor_test.go
- scheduled_task.go
- stats.go
- storage.go
- storage_test.go
- task.go
- task_scheduler.go
- task_scheduler_test.go
Includes a store, scheduler, cli, maintenance admin functions
prom stats and HA
> (#18) initial scheduled tasks implementation

- go.mod
- go.sum
- scheduled_task.go
> (#18) add json decoration for some schedule fields

- ajc/task_command.go
- generators/fs/godocker/Dockerfile.templ
> (#63) consistency update for the generated containers

- ajc/task_command.go
- errors.go
- generators/fs/godocker/Dockerfile.templ
- generators/fs/godocker/main.go.templ
- generators/godocker.go
- generators/package.go
- go.mod
- go.sum
- mux.go
- mux_test.go
- testdata/failing-handler.sh
- testdata/passing-handler.sh
> (#68) make external command handlers usable via go api and asyncjobs file

- ajc/package_command.go
- request_reply_handler.go
> (#68) cosmetic updates for packaging command

- .github/workflows/test.yaml
- client_options.go
- errors.go
- generators/fs/godocker/main.go.templ
- task.go
Signed-off-by: Roland Pienaar <roland.pienaar@workday.com>
> (#73) resolve types handling of discard types from yaml

- client_test.go
- task.go
Signed-off-by: Roland Pienaar <roland.pienaar@workday.com>
> (#73) also handle completed as a discard name

- README.md
- go.mod
- go.sum
> (misc) update dependencies

- ajc/info_command.go
- go.mod
- go.sum
- storage.go
This is not the full storage management feature I have in mind
but enough to get the most annoying niggles sorted now
> (#67) add some init options to ajc info

- docs/config.toml
- docs/static/css/theme-asyncjobs.css
> (misc) small doc template tweaks

- README.md
- docs/config.toml
- docs/content/_index.md
- docs/content/overview/features.md
> (misc) update doc themes, mention docs in readme

- generators/fs/godocker/Dockerfile.templ
- go.mod
- go.sum
- processor.go
> (#98) avoid job processor stalling after repeated task not found states

- ajc/main.go
> (#100) improve usage output

- ajc/main.go
> (misc) update fisk dependency

- ajc/main.go
- storage.go
Also default to 10000 when no limit is given
> (#104) avoid duplicates in task list
